import type { NextPage } from "next";
import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { toast } from "react-toastify";

import {
  Header,
  SocialMedia,
  HeaderContent,
  Text,
  PortalDivider,
  Main,
  SearchBar,
  SearchBarContent,
  SearchTypesContainer,
  SearchInput,
  CharactersContainer,
  PaginationContainer,
  Footer
} from "../styles/pages/home";

import { Waves } from "../components/Waves";
import { ButtonType } from "../components/ButtonType";
import { Card } from "../components/Card";

import logoLinkedinImg from "../assets/logoLinkedin.svg";
import logoGithubImg from "../assets/logoGitHub.svg";
import rectangleDownImg from "../assets/RectangleDown.svg";
import rectangleUpImg from "../assets/RectangleUp.svg";
import portalDividerImg from "../assets/PortalDivider.png";
import headerImg from "../assets/headerImg.png";
import searchImg from "../assets/searchIcon.svg";

import { HeaderMenu } from "../components/HeaderMenu";

import { CharacterProps } from "../types/character";
import { PagesInfo } from "../types/pagesInfo";

import Pagination from "@mui/material/Pagination";
import Stack from "@mui/material/Stack";

const initialPageState = {
  count: 826,
  pages: 42,
  next: "https://rickandmortyapi.com/api/character/?page=2",
  prev: null
};

const Home: NextPage = () => {
  const [characters, setCharacters] = useState<CharacterProps[]>([]);
  const [search, setSearch] = useState("");
  const [activeGender, setActiveGender] = useState("");
  const [pagination, setPagination] = useState<PagesInfo>(initialPageState);
  const [currentPage, setCurrentPage] = useState(1);

  async function handleSearchToGender(gender: string) {
    try {
      const removeGenderFilter = gender === activeGender;
      setActiveGender(removeGenderFilter ? "" : gender);

      const { data } = await axios.get("https://rickandmortyapi.com/api/character/", {
        params: { gender: !removeGenderFilter ? gender.toLowerCase() : "", name: search }
      });

      setCurrentPage(1);
      setPagination(data.info);
      setCharacters(data.results);
    } catch (error) {
      toast.error("Character not found.");
    }
  }

  async function handleSearchCharacters(e: { preventDefault: () => void }) {
    e.preventDefault();
    try {
      const { data } = await axios.get("https://rickandmortyapi.com/api/character/", {
        params: { name: search, gender: activeGender }
      });

      setCurrentPage(1);
      setPagination(data.info);
      setCharacters(data.results);
    } catch (error) {
      toast.error("Character not found.");
    }
  }

  const handleChange = async (event: React.ChangeEvent<unknown>, value: number) => {
    const { data } = await axios.get("https://rickandmortyapi.com/api/character/", {
      params: { gender: activeGender.toLowerCase(), name: search, page: value }
    });
    setCurrentPage(value);
    setPagination(data.info);
    setCharacters(data.results);
  };

  const fetchCharacters = async () => {
    const { data } = await axios.get("https://rickandmortyapi.com/api/character/");
    setCurrentPage(1);
    setActiveGender("");
    setPagination(initialPageState);
    setSearch("");
    setCharacters(data.results);
  };

  useEffect(() => {
    fetchCharacters();
  }, []);
  return (
    <>
      <Head>
        <title>Rick and Morty API</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header>
        <HeaderMenu />

        <HeaderContent>
          <Text>
            <h1>RICK AND MORTY</h1>
            <p>
              Rick and Morty is the Emmy award-winning half-hour animated hit comedy
              series on Adult Swim that follows a sociopathic genius scientist who drags
              his inherently timid grandson on insanely dangerous adventures across the
              universe. Rick Sanchez is living with his daughter Beth`s family and
              constantly bringing her, his son-in-law Jerry, granddaughter Summer, and
              grandson Morty into intergalactic escapades.
            </p>
          </Text>
          <PortalDivider>
            <Image src={rectangleDownImg} alt="rectangle down" />
            <Image src={portalDividerImg} alt="portal divider" width={60} height={60} />
            <Image src={rectangleUpImg} alt="rectangle up" />
          </PortalDivider>
          <div>
            <Image src={headerImg} alt="Rick and morty" width={557} height={564} />
          </div>
        </HeaderContent>

        <Waves />
      </Header>
      <Main>
        <SearchBar>
          <SearchBarContent>
            <SearchTypesContainer>
              <button onClick={fetchCharacters}>Inicio</button>
              <h2>Search by Gender</h2>
              <div>
                <ButtonType
                  name="Male"
                  color="male"
                  isActive={activeGender === "Male"}
                  onClick={(name) => handleSearchToGender(name)}
                />
                <ButtonType
                  name="Female"
                  color="female"
                  onClick={(name) => handleSearchToGender(name)}
                  isActive={activeGender === "Female"}
                />
                <ButtonType
                  name="Genderless"
                  color="genderless"
                  onClick={(name) => handleSearchToGender(name)}
                  isActive={activeGender === "Genderless"}
                />
                <ButtonType
                  name="Unknown"
                  color="unknown"
                  onClick={(name) => handleSearchToGender(name)}
                  isActive={activeGender === "Unknown"}
                />
              </div>
            </SearchTypesContainer>
            <SearchInput>
              <input
                type="text"
                placeholder="Seach character"
                onChange={(e) => setSearch(e.target.value)}
              />
              <button onClick={handleSearchCharacters}>
                <Image src={searchImg} alt="Search icon" />
              </button>
            </SearchInput>
          </SearchBarContent>
        </SearchBar>

        <CharactersContainer>
          {characters &&
            characters.map((character) => (
              <Card character={character} key={character.id} />
            ))}
        </CharactersContainer>

        <PaginationContainer>
          <Stack spacing={5}>
            <Pagination
              count={pagination.pages}
              color="primary"
              page={currentPage}
              variant="outlined"
              shape="rounded"
              onChange={handleChange}
            />
          </Stack>
        </PaginationContainer>

        <Footer>
          <p>Dados pegos da API - rickandmortyapi</p>

          <SocialMedia>
            <a
              href="https://www.linkedin.com/in/gabriel-william-serrano/"
              target="_blank"
              rel="noreferrer"
            >
              <Image src={logoLinkedinImg} alt="logo linkedin" />
            </a>
            <a
              href="https://github.com/Gabriel-WilliamS"
              target="_blank"
              rel="noreferrer"
            >
              <Image src={logoGithubImg} alt="logo github" />
            </a>
          </SocialMedia>
        </Footer>
      </Main>
    </>
  );
};

export default Home;
